alias ll="ls -l"
alias la="ls -all"
alias sbp="source ~/.bash_profile"
alias ackri="ack -r -i"
alias gs="git status"
alias gcam="git commit -a -m"
alias gp="git push"
alias reset_keymap="setxkbmap -layout us"
